### ISSUE TITLE
Typogrify

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#1]
`se typogrify .` makes a few final changes (to whitespace characters)

Replace dipthongs - eg spiræa -> spirea (M-W) or spiraea (M-W variant) 
There are 20 instances æ to review.

Although cañon is in Miriam Webster (as a less common spelling) I would suggest amending it to canyon throughout using a commit prefixed with [Editorial] as this would be the more modern spelling. Searching online for "Tuolumne Cañon" only brings up older works suggesting that this spelling is no longer widely used even as a local spelling.

**Comment by laurakwriting** [comment]
Thank you! Fixes are included in the following commits:

- bb27b29 - [Editorial] Run se typogrify again to clean up whitespace characters
- d92e48e - [Editorial] Replace dipthongs
- 6624b55 - [Editorial] Replace cañon with canyon (modernize spelling)

**Comment by laurakwriting** [comment]
Hi Michael, 
The fixes for this issue are now ready for review,
Thank you,
Laura

**Comment by laurakwriting** [comment]
Took care of several more cañon to canyon replacements previously missed:

- 811e6db [Editorial] More cañon to canyon replacements (modernize spelling)
