### ISSUE TITLE
Producer Website

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#2]
Producer website links to a 403 error in [content.opf](https://github.com/laurakwriting/john-muir_my-first-summer-in-the-sierra/blob/master/src/epub/content.opf) and [colophon.xhtml](https://github.com/laurakwriting/john-muir_my-first-summer-in-the-sierra/blob/master/src/epub/text/colophon.xhtml).

**Comment by laurakwriting** [comment]
Fixed - Sorry about that! I've now added a simple landing page to https://lauraklappenbach.com. I'm currently re-developing that website offline and forgot the live site didn't have a simple index page.
