### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#3]
`<i>` with no semantics - these look like they should be `<em>` tags in each case

- Chapter 1 "or rather \<i>in\</i> the blue air"
- Chapter 3 "Well, how do you like \<i>my\</i> beans?"
- Chapter 3 "\<i>Yes, sir\</i>, that \<i>is\</i> good coffee."
- Chapter 7 "thought Professor Butler \<i>was\</i> in the valley"
- Chapter 7 "Why? Do \<i>you\</i> know him?" x2

**Comment by laurakwriting** [comment]
Fixes in this commit:

- 1ecf2c4 Semantics corrections (i > em)

**Comment by laurakwriting** [comment]
Missed one - fixed here:

- 4d7f20a One more semantics corrections (i > em)

**Comment by laurakwriting** [comment]
Hi Michael, 
The fixes for this issue are now ready for review,
Thank you,
Laura
