### ISSUE TITLE
CSS Steamlining

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#5]
The class `no-header` is redundant. The only time it is used in inconjunction with `section[epub|type~="z3998:diary"]` and this can be targetted directly (as the only time it occurs is with `class="no-header"`). I would remove references to `no-header` in the `*.xhtml` and `local.css` (you can actually remove the `section` reference in local.css as well) This would lead to 
```
section[epub|type~="z3998:diary"].no-header{
	margin: 1em;
}
```
becoming
```
[epub|type~="z3998:diary"]{
	margin: 1em;
}
```
You can also remove the similar entry with `margin-left` and `margin-right` declarations as they are redundant.
	
```
p[epub|type~="se:diary.dateline"]{
	text-align: right;
}
```
is always `p` so can be reduced to 
```
[epub|type~="se:diary.dateline"]{
	text-align: right;
}
```
It would also be helpful to try to prevent page breaks after that element so including `page-break-after: avoid;` there would help with that as well.

```
[epub|type~="z3998:diary-entry"] p[epub|type~="se:diary.dateline"] + p,
figure + p{
	text-indent: 0;
}
```
`dateline` is always nested within `diary-entry` so this can be reduced to 
```
[epub|type~="se:diary.dateline"] + p,
figure + p{
	text-indent: 0;
}
```

There is no exception to the pattern
```
<p epub:type="se:diary.dateline">
	<i>August 13.</i>
</p>
```
so it would be more efficient to use
```
<p epub:type="se:diary.dateline">August 13.</p>
```
and change 
```
[epub|type~="se:diary.dateline"]{
	text-align: right;
}
```
to 
```
[epub|type~="se:diary.dateline"]{
	text-align: right;
	font-style: italic;
}
```

**Comment by laurakwriting** [comment]
Please see the following commit for updated css:
- dfb7d6f7 CSS streamlining

And this commit for updated xhtml files:
- 5aca048 CSS streamlining to fix diary datelines and remove no-header
