### ISSUE TITLE
Descriptions of the book

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#6]
Long and Short Descriptions need strengthened - I don't really get a sense of _why_ I should read the book from the descriptions!
BTW, I hate writing these. For the short description we tend to avoid using the names of the characters and only use a single sentence. Maybe something like...

> A Scottish-American naturalist makes a journey to the high country surrounding the headwaters of the Merced and Tuoloumne rivers in the Sierra Nevada and records what he sees in a diary.

The long description should ideally be more than one paragraph and give more details about background as well as what to expect.

**Comment by laurakwriting** [comment]
I really struggled with writing these  Long/Short Descriptions. I'm not great at this kind of writing but made attempts to improve and expand. Please let me know what you think.

Updates in this commit:
- 53e1f14 Revisions to short/long descriptions in content.opf

**Comment by michael-77** [comment]
Looks good.
