### ISSUE TITLE
Missing Source

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#7]
The Hathi Trust source needs to be added to `content.opf`

**Comment by laurakwriting** [comment]
Fixed - added as line 52:
`<dc:source>https://catalog.hathitrust.org/Record/007668397</dc:source>`

**Comment by laurakwriting** [comment]
Fix included in the following commit:

- 9b0c27b Adds missing dc:source (hathitrust) to content.opf
